### ISSUE TITLE
job.vim shouldn't be just copy of async.vim/autoload/job.vim

### ISSUE THREAD

**Issue by mkwork** [prabirshrestha/vim-lsp#1]
There should be introduced any dependency management mechanism, while async.vim can be useful as standalone library, but just copying it in your plugin's will lead to such behavior from other plugin developers.  So there can be too big wish  just to use your own modified copy of job.vim instead of contribute back.

**Comment by prabirshrestha** [comment]
Plugin authors are free to use this library directly as a plugin dependency (`Plug 'prabirshrestha/async.vim'`) or copy paste the code in their repo.

This github repo is more of a util function so others can understand how lsp protocol works. Ideally people would use a full blown lsp server https://github.com/tjdevries/nvim-langserver-shim that ships with vim-lsp instead of using this directly.

**Comment by mkwork** [comment]
Just imho. Something in style of "don't repeat yourself" idiom.

**Comment by mkwork** [comment]
Cute. Thank you!
