### ISSUE TITLE
How to start the language server only when a specific file exists

### ISSUE THREAD

**Issue by yaegassy** [prabirshrestha/vim-lsp#1061]
Is there a way to start the language server only when a specific file exists?

Visual Studio Code extention and coc.nvim extention can be configured with activationEvent. Ref: [workspaceContains in Activation Events](https://code.visualstudio.com/api/references/activation-events#workspaceContains)

Also, in the case of registering the language server directly in coc.nvim, there is a setting called `requireRootPattern`. Ref: [coc.nvim wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers)

> `requireRootPattern` when this is true, the language server will only start when any matched rootPatterns found.

**Comment by prabirshrestha** [comment]
cmd in register_server is a func. If you return empty array it will ignore.

**Comment by yaegassy** [comment]
@prabirshrestha This assumes the case where cmd exists but the configuration file does not.

For example, if you don't have the configuration file (`.config/rome.rjson`) for `rome` langauge server, the server will start up, but nothing will work.

For example, PHP's `psalm-language-server` will be **"exited"** if the configuration file (`psalm.xml` or `psalm.xml.dist`) does not exist.

**Comment by prabirshrestha** [comment]
vim doesn't support a concept of workspace hence for vim-lsp once u start the server no matter which file you open in which folder it is considered as a single folder with workspace. so the only way to prevent is to avoid starting the server in the first place.

The reason I have not implemented this is due to lack of workspace support in vim and stabilizing of the lsp api. Now that it is in api, I have proposed an api in https://github.com/vim/vim/issues/7748. It is something I do want to support it but would like vim to natively support the concept first.

**Comment by yaegassy** [comment]
@prabirshrestha Thanks reply 
Thank you for the detailed explanation. I understand now.

**Comment by yaegassy** [comment]
As an addendum to this issue, coc.nvim seems to take the approach of resolving the issue from an open file or explicitly adding a workspace setting. Ref: [Using workspaceFolders](https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders)
