### ISSUE TITLE
Support autowriteall

### ISSUE THREAD

**Issue by astifter** [prabirshrestha/vim-lsp#1070]
I'm using autowrite and autowriteall to never have to manually save files (and backup, patchmode and Git to prevent the occasional screwup) :)

When doing a code edit and using any of the Lsp commands to navigate to a different file the window is split with the changes staying unsaved. This gets cumbersome because I have to change back to the originating window and close it manually.

I would prefer autowriteall to be honoured in this case and, upon navigation the file saved and the current buffer replaced with the destination file.

(Ah: using latest nvim built from master and latest vim-lsp.)

**Comment by prabirshrestha** [comment]
Do you know which autocmd is fired? Once we know that we can add it here https://github.com/prabirshrestha/vim-lsp/blob/5fc5e26f5fadd5a5335fb9146706b8c2bf0d70a0/autoload/lsp.vim#L208-L212

based on the docs it writes the contents to the file so `BufWritePre` could help here. Can you try adding the following line and see if it works. 

```vim
 autocmd BufWritePre * call s:on_text_document_did_change() 
```

if that works, we can add this only if `autowrite` or `autowriteall` is enabled. Also you can try `:e` instead of closing and opening.

**Comment by astifter** [comment]
Nope, sorry. That doesn't work. AFAICS from the logs the s:on_text_document_did_close() trigger gets fired when the new buffer is opened. Maybe we can place some autowrite/autoclose code there?
Maybe here? 
https://github.com/prabirshrestha/vim-lsp/blob/882376cc666fa0cd490843529d04c028dd938738/autoload/lsp/utils/location.vim#L5
