### ISSUE TITLE
Diagnostics change highlighting

### ISSUE THREAD

**Issue by harshad1** [prabirshrestha/vim-lsp#1167]
![image](https://user-images.githubusercontent.com/1940940/119047430-c48e4300-b972-11eb-90bb-c4b6c6d551b4.png)

As seen above, the diagnostics change the highlighting for the function signature to that of the diagnostic. This makes the code less readable.

Also note the highlighting on `baz, [3, 3, 2]`

**Comment by prabirshrestha** [comment]
This is most likely due to your colorscheme not supporting highlight groups such as `LspErrorHighlight`. It it doesn't exist we default it to `Error` i.e. `highlight link LspErrorHighlight Error`. Feel free to change the highlight color or disable the feature by `let g:lsp_diagnostics_highlights_enabled=0`.

https://github.com/prabirshrestha/vim-lsp/blob/1f98a0656620bfc03dcb8bad87aa76a6304b3b73/doc/vim-lsp.txt#L501-L517
