### ISSUE TITLE
Broken changes?

### ISSUE THREAD

**Issue by zoumi** [prabirshrestha/vim-lsp#1188]
After I update to the newest version of vim-lsp (from a version in May).
When I startup the gvim I got this:
![Snipaste_2021-06-08_13-59-24](https://user-images.githubusercontent.com/5162901/121131698-bdb46b00-c862-11eb-9dda-bb6a221af609.jpg)
when I trig autocomplete:
![InkedSnipaste_2021-06-08_13-55-26_LI_Moment](https://user-images.githubusercontent.com/5162901/121131644-a8d7d780-c862-11eb-8203-e9a5256b95e2.jpg)

My C source file contains Non ASCII chars in comment.

I'm using:
gvim 8.2 @ Windows 10.
clangd

**Comment by prabirshrestha** [comment]
could you try this branch. https://github.com/prabirshrestha/vim-lsp/tree/client-parse

**Comment by zoumi** [comment]
I had test wtih client-parse branch. The "throwpoint" message is still there, but I the error message was gone.
![Snipaste_2021-06-11_22-15-19](https://user-images.githubusercontent.com/5162901/121701910-f9ba2b00-cb03-11eb-867a-5f9cf9524cf2.jpg)

I will create a minimal project to test it later and put vim-lsp's log file here.
Thank you for your response.

**Comment by hrsh7th** [comment]
I'm wondering if [the line](https://github.com/prabirshrestha/vim-lsp/blob/client-parse/autoload/lsp/client.vim#L67) is the cause.

**Comment by zoumi** [comment]
![Snipaste_2021-06-12_09-43-13](https://user-images.githubusercontent.com/5162901/121762206-0de34400-cb67-11eb-89ac-137b62bcd693.jpg)

[vim_lsp.log](https://github.com/prabirshrestha/vim-lsp/files/6641507/vim_lsp.log)

It's hard to trigger this bug with small c project. I don't know how to reproduce it exactly.

**Comment by prabirshrestha** [comment]
@hrsh7th Removing `timer_start` will cause stackoverflow since rust sends a lot of work done progress message in a short time. Sees like we need to convert it to `loop` without function overhead if we want to remove timer. 

Feel free to try this repo https://github.com/prabirshrestha/objstor with the following vimrc with rust-analyzer with `g:lsp_work_done_progress_enabled=1`

```vim
Plug 'itchyny/lightline.vim'

let g:lightline = {
  \ 'colorscheme': 'solarized',
  \ 'active': {
  \   'left': [
  \     ['mode', 'paste'],
  \     ['lsp_progress'],
  \   ],
  \ },
  \ 'component_function': {
  \   'lsp_progress': 'MyLspProgress'
  \ },
  \ }

let g:lsp_work_done_progress_enabled = 1
function! MyLspProgress() abort
  let l:progress = lsp#get_progress()
  if empty(l:progress) | return '' | endif
  let l:progress = l:progress[len(l:progress) - 1]
  return l:progress['server'] . ': ' . l:progress['message']
endfunction

augroup my_lightline_lsp
  autocmd!
  autocmd User lsp_progress_updated call lightline#update()
augroup END
```

Not having it in timer also seems to cause vim-lsp to slow down.

What we need to do is most likely append to array as part of stdout and then parse on the next tick so it doesn't spend too much time on processing. Javascript has setImmediate/requestAnimationFrame/process.nextTick in vim we would need to have something equivalent or use `timer_start(0, cb)`.

For now I'm reverting the perf PR. https://github.com/prabirshrestha/vim-lsp/pull/1199

**Comment by prabirshrestha** [comment]
I have temporarily reverted the perf changes in master so we should be good for now. Perf is still something I would like to invest in the near future.

**Comment by prabirshrestha** [comment]
@hrsh7th I ported your fixes to https://github.com/prabirshrestha/vim-lsp/tree/array-perf branch. While I no longer see the error I still do see the perf issue in the beginning where I can't use my cursor for few seconds. I think we still need to use the timer_start to get the best experience.

**Comment by hrsh7th** [comment]
@prabirshrestha I'm sorry I didn't contact you when I updated it.
Thank you for your investigation. I will consider how to use  timer_start.
