### ISSUE TITLE
Weird preview highlights

### ISSUE THREAD

**Issue by fdelacruz** [prabirshrestha/vim-lsp#1240]
before:
![Screen Shot 2021-12-11 at 11 01 48 AM](https://user-images.githubusercontent.com/148098/145684431-1779cc19-c709-444a-899b-332b9cf63b99.png)

after:
![Screen Shot 2021-12-11 at 11 02 14 AM](https://user-images.githubusercontent.com/148098/145684379-ecf6d06b-d391-4746-b343-cac8c701b82a.png)

**Comment by fdelacruz** [comment]
I'm referring to the highlighted single quotes in the second image. 
How do you turn it off from them appearing.

**Comment by fdelacruz** [comment]
> hey how did you solve this? I am having same issue.

@hillyu Hi, I have since moved over to neovim for my lsp needs. It just works without annoying these "highlight issues".
Don't get me wrong, I love vim for everything else but my OCD just couldn't stand this. jaja
I'm really sorry I can't be of much help.

**Comment by hillyu** [comment]
@fdelacruz Thanks for the info and glad it worked out well for you by using neovim, The native LSP support is pretty nice.
I figured out that my issue is actually a different one. For me, it's the wrong highlight color in popup menu. Turns out my `Pmenu` has `cterm-reversed` set. Once I cleared  that option and reconfigured the highlight color, the popup menu started to show the correct color.
