### ISSUE TITLE
long running indexer for vim-lsp

### ISSUE THREAD

**Issue by walkerlala** [prabirshrestha/vim-lsp#1243]
I am using ccls + vim-lsp.

It seems that on vim startup, the code index is usually not complete, so I cannot find reference and have to retry.

Is there any way to run a long-running ccls at backgroud (i.e., as a daemon) and connect to it at vim startup so that my code index is always fresh ?

**Comment by prabirshrestha** [comment]
There isn't much we can do since the process we create is shutdown by the OS when vim exits. There are several options.

1. Request ccls to improve caching and possibly use disk caching.
2. Request ccls to support daemon mode similar to gopls. https://github.com/golang/tools/blob/master/gopls/doc/daemon.md. 
3. Create a proxy language server to support daemon mode for any lang servers.

2nd might be really worth it for ccls.
