### ISSUE TITLE
Support multiple LSP server instances per filetype, by root_uri

### ISSUE THREAD

**Issue by gwicke** [prabirshrestha/vim-lsp#157]
Some of us are working on multiple projects using the same filetype, and in general we cannot expect the same LSP server instance to work across all of them. However, to avoid repetitive config sections it would be nice to still support sharing *configs* across multiple projects when settings other than `root_uri` are identical.

Sketch:
- Start one LSP server instance per root_uri, if the root_uri is a prefix of the buffer path.
- Select the appropriate LSP server for a given buffer using root_uri.

**Comment by prabirshrestha** [comment]
This is official supported by concept of workspace folders in LSP v3. Other editors such as vscode, sublime text has workspace so it is very easy to map to a workspace. I started this when lsp was v2 which didn't have workspace. I had thought of workspace concept even before lsp supported it but it wasn't easy to satisfy everyone since I don't know one user would define a workspace. Might be good if vim contains the concept of workspace then there is a unified way to create workspace. Or have a hook that allows users to notify return workspace and they can use any plugins they want.

**Comment by prabirshrestha** [comment]
closing to cleanup stale issues.
