### ISSUE TITLE
Does not send `initialized` method

### ISSUE THREAD

**Issue by pt-stripe** [prabirshrestha/vim-lsp#166]
Hi! We're developing a typechecker for Ruby and with it an LSP implementation (https://sorbet.run/) . 

In trying to hook it up with your plugin we found you aren't sending the `initialized` response. As per the spec the handshake should be:

```
  -> initialize(request than expects a response)
  <- initialize response
  -> initialized(notification that does not expect response)
```

Do most LSP servers not expect this? We were just trying to code to the spec and are surprised you don't sent that message.

Thanks!

**Comment by megalithic** [comment]
exciting project! will be watching closely. were you able to get other ruby  LSP projects working with vim-lsp? such as solargraph perhaps? good luck!

**Comment by prabirshrestha** [comment]
Seems like it is not supported in v2 spec hence I most likely never implemented it since vim-lsp was written during v2 era even though most servers were still in v1.

https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md

vim-lsp does implement `initialize`. It came as a request to cquery server. But doesn't send the `initialized`. Seems like a breaking change to me. Or I need to provide a way to pass protocol version during config which I have been trying to avoid at all cost if possible. Another option would be to pass a flag that says to send `initialized` request. Here is the initialize PR https://github.com/prabirshrestha/vim-lsp/pull/62

Might be start a thread in the LSP github issue on what the behavior should be?

**Comment by prabirshrestha** [comment]
Could you try https://github.com/prabirshrestha/vim-lsp/pull/317

**Comment by prabirshrestha** [comment]
This was implemented in https://github.com/prabirshrestha/vim-lsp/pull/317
