### ISSUE TITLE
Running cquery+vim-lsp spawns a server for each instance.

### ISSUE THREAD

**Issue by armax00** [prabirshrestha/vim-lsp#281]
Hi there!

I have noticed that using cquery and vim-lsp, I am essentially spawning one cquery server for each vim instance which is not ideal, in fact with a big project I am running into issues like PC frozen and similar due to the excessive use of memory (hence swapping).

Should it be possible to configure vim-lsp to have a single cquery instance running on a project and have multiple vim instances talk to it?

**Comment by mattn** [comment]
Currently, vim-lsp does not support socket connection. And also, as far as I can see output of `cqurery --help`, cquery does not support socket server.

**Comment by armax00** [comment]
Fair enough. I'll try to get in touch with the cquery author and see if that is something that could be done. I would say, that would make things quite nice for integrating multiple plugins with it.

**Comment by mattn** [comment]
At least, Vim start one instance of cquery per one Vim process. So if you edit files using window splitting, cquery is spawned once. (until cquery will support socket server)

**Comment by armax00** [comment]
That is surely the case, but the problem persists if one uses multiple plugins as I am doing since I am using both vim-lsp and ALE with cquery as a backend.

**Comment by mattn** [comment]
Ah, make senese.

**Comment by prabirshrestha** [comment]
This is something I have faced too and wanted to fix it myself. I usually use only typescript and the server does start pretty fast around <5-10 sec on cold start and hasn’t bothered much since I usually have my main vim instance always running although it changes how I use vim.

Http and websockets was out of question because it provides a security loophole as in any program can now access it easily. And if you have a misconfigured firewall it is even worse. (I do want vim to support both http and web sockets client and server as it does allow plugin authors to easily innovate on).

I haven’t tried it but this could work if you are on non-windows machine.
- http://www.brain-dump.org/projects/abduco/
- https://github.com/crigler/dtach

Tmux is the biggest terminal command line app I miss on windows and one of my goal is to port dvtm and abduco to rust this year while I’m learning rust and make it cross platform. It is going take a lot of time for me given how hard rust is, so in the meantime if anyone is proficient in c, pty and terminal feel free to port those apps.

**Comment by prabirshrestha** [comment]
This is an expected behavior.
