### ISSUE TITLE
LSP signs are broken on Neovim

### ISSUE THREAD

**Issue by edganiukov** [prabirshrestha/vim-lsp#322]
Neovim has no patch-8.1.0772 `:echo has('patch-8.1.0772')` returns `0`.

**Comment by Shougo** [comment]
It is intended changes.
Current vim-lsp uses new sign APIs.

neovim does not support sign APIs in Vim8.1 yet.

**Comment by prabirshrestha** [comment]
Unfortunately neovim doens't support. You can follow the issue at https://github.com/neovim/neovim/issues/8668

**Comment by edganiukov** [comment]
Seems like the only one way so far is to rollback.

**Comment by prabirshrestha** [comment]
Virtual Text PR was recently merged. As a workaround you could try using it. https://github.com/prabirshrestha/vim-lsp/pull/336

There was also a refactor to allow diagnsotics without sign columns at https://github.com/prabirshrestha/vim-lsp/pull/313 which has been merged to master.

**Comment by prabirshrestha** [comment]
There is a PR out in neovim for signs support. Please try it out and provide feedback upstream https://github.com/neovim/neovim/pull/10059

**Comment by jerdna-regeiz** [comment]
Unfortunate `:echo has('patch-8.1.0772')` will still be `0` even with the PR. But it works with vim-lsp signs when removing the explicit check for patch-8.1.0772 and only checking the existence of the api functions.

**Comment by prabirshrestha** [comment]
You would have to temporarliy remove that to try it out and when the PR gets merged in we can change the version check.

**Comment by edganiukov** [comment]
I removed temporally `has('patch-8.1.0772')` and sings are back.

**Comment by jerdna-regeiz** [comment]
The PR neovim/neovim#10059 (and a corresponding bug) is fixed now.
When changing the check signs are working great in neovim master now =)

**Comment by aktau** [comment]
Indeed it works pretty well if one just removes `has('patch-8.1.0772')`. I wonder why checking for `exists('*sign_define')` isn't sufficient. Looking at the patch itself, it seems to have been just a refactoring: https://github.com/vim/vim/pull/3819.

**Comment by prabirshrestha** [comment]
We should still look for patch number for neovim since some people have old version and it consumes everyone time on why it isn't working. Feel free to send a PR.

**Comment by aktau** [comment]
> We should still look for patch number for neovim since some people have old version and it consumes everyone time on why it isn't working. Feel free to send a PR.

Why specifically this patch number though. It looks like a refactor.

Also, to see whether we should have an additional check for a patch number it'd be useful to know if there was ever a version of Vim8 or Neovim that:

  1. Had `exists('*sign_define')`. And:
  2. Had a bug that caused this functionality to not work properly.

Since `patch-8.1.0772` is a refactoring, it does not appear to have fixed any bugs. Maybe it's another patch we should be checking for?

(For Neovim, this is not true as it was all merged in a single PR. For Vim I'm unsure but you may know since you added the check.)

So maybe the enablement check can be:

```vim
exists('*sign_define') && (has('nvim') || has('patch-8.1.0772'))
```

How do you feel about that?

**Comment by jerdna-regeiz** [comment]
Since the New api in vim was introduced, there was no breaking bug, but memory leaks. Most of the related patches did either refactor or improve performance.

Depending on the usage, following patches might be important:
* vim-patch:8.1.0679: sign functions do not take buffer argument as documented
* vim-patch:8.1.0717: there is no function for the ":sign jump" command

Guess the proposed check looks good, as nvim either has no sign_define or all of the mentioned patches.

**Comment by aktau** [comment]
Thanks for looking at it. I'm at work which makes it difficult to send a patch. It would be neat if somebody else could make this quick change. Thanks a lot!

**Comment by prabirshrestha** [comment]
This should be fixed. Please update to latest neovim and vim-lsp.
