### ISSUE TITLE
Consider echo'ing instead of quickfixes for Hover

### ISSUE THREAD

**Issue by djrenren** [prabirshrestha/vim-lsp#34]
Would it make more sense to `echo` or `echom` the hover information? the quickfix list seems kinda obtrusive.

I realize this gets sticky when there are multiple servers providing hover information. My solution would be to select the first non-empty response and display that. Thoughts?

**Comment by prabirshrestha** [comment]
Sure. Feel free to send a PR.

**Comment by lmilasl** [comment]
About that, I have a solution that uses the preview window instead of the quickfix. any interest with it ?

**Comment by prabirshrestha** [comment]
@lmilasl that would be good too.

I have always wanted to is have a comma separate option for UI. Use the first one if possible and fallback to next.  `let g:lsp_hover_ui = 'echo,preview'`. 
In this case it doesn't make much sense but for other you could have something like `let g:lsp_document_symbols_ui = 'fzf,ctrlp,quickfix' ` and so on.

**Comment by lmilasl** [comment]
Why not start only with builtins ?
in a first iteration there could be a function handle_message_display dispatching according to g:lsp_document_symbol_ui to either echo, preview, balloon-expr or quickfix.
But again some of these make more sense for specific contexts. Diagnostics and fixmes definitely belong to quickfix but documentation fits better in either preview or balloon-expr.
I currently have some code that strictly replaces the quickfix by the preview window in handle_hover. If you want I can already make a pull request with it but it has none of the customizability you're talking about.
Otherwise I could try implementing a more flexible approach but before that I'd like to have a better view of the behaviors wanted for message display.

**Comment by hauleth** [comment]
I just come here to create that issue. However I have a little bit different idea than @prabirshrestha, `LspHover` should always `echo` data and there should be additional `LspDocs` that would send `textDocument/signatureHelp` message to server and that would be displayed in window.

**Comment by hauleth** [comment]
After checking this out I have found that there is small problem, `textDocument/hover` not always will return one line, which can be troublesome. Instead for now I am creating preview window with content returned by server (for now I always assume Markdown document, but can be changed in future). This works quite well

![example](https://user-images.githubusercontent.com/291639/34457665-253f93a0-edb8-11e7-9e94-d60123f91bb7.png)

The solution would be to make `LspHover` `echo` only first line returned from server, this will not always work perfectly, but should be GoodEnough™.
