### ISSUE TITLE
Should refactor omni.vim to support `completionItem/resolve`.

### ISSUE THREAD

**Issue by hrsh7th** [prabirshrestha/vim-lsp#628]
Currently, implementation store some values to user_data but it should be changed.

I think, to support `completionItem/resolve` needed storing `server_name` and `completion_item` to user_data.

I bit worry about the change breaks some other plugin integrations but I couldn't find the plugin uses `vim-lsp/textEdit` etc.

--- Updated
- fix example key name.

**Comment by prabirshrestha** [comment]
I explicitly don't use `lsp/textEdit` as changing it could break any plugins. There is also no standard on this. Instead we use custom `vim-lsp/*`.

https://github.com/prabirshrestha/vim-lsp/blob/9becd620b773ec3bf15ed8435d02af7823d29f0b/autoload/lsp/omni.vim#L40-L44

Also [asyncomplete-lsp](https://github.com/prabirshrestha/asyncomplete-lsp.vim) also calls `lsp#omni#get_vim_completion_item` which is used by vim-lsp omnifunc too.

https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/9e7b2492578dca86ed12b6352cb56d9fc8ac9a6e/plugin/asyncomplete-lsp.vim#L88

As long as https://github.com/prabirshrestha/vim-lsp/blob/9becd620b773ec3bf15ed8435d02af7823d29f0b/autoload/lsp/omni.vim#L240 is called using those should be ok.

We can use `vim-lsp/serverName` to store the server name and `vim-lsp/completionItem` to store the original lsp completion item.

**Comment by hrsh7th** [comment]
If ok to remove `vim-lsp/textEdit` and others and the add `vim-lsp/serverName` and `vim-lsp/completionItem`, I will try to improve omni.vim.

**Comment by prabirshrestha** [comment]
No one except vim-lsp uses that so should be ok to refactor.

But we should be careful about perf since `user_data` can only contain string. Using `json_encode`/`json_decode` might be expensive specially if no one will actually use the values. It might make sense to just store some index and then expose another api such as `lsp#omni#get_completion_item('0')` and if it return null it means it doesn't exists else it will return the actual completion item. When the pum closes we should also clear that dictionary.

Instead of just 0, we could prefix the user_data with `vim-lsp/index/0` so we know that item was generated by vim-lsp and can ignore other items. This is useful when you are using plugins like asyncomplete which may use multiple sources that is not vim-lsp.

Thoughts?

**Comment by hrsh7th** [comment]
Ah! I think so too.
I will implement the solution, when trying the improvements

**Comment by hrsh7th** [comment]
I'm trying to implement the solution that uses `vim-lsp/itemIndex` key.

But it can't implement simply.
The reason is that `CompleteDone` is called multiple times during completion.
So can't clear current completion items at right timing.

I try to implement that stores `CompletionItem` to user_data.

**Comment by hrsh7th** [comment]
The PR is here https://github.com/prabirshrestha/vim-lsp/pull/637.

**Comment by hrsh7th** [comment]
Fixed in #637
