### ISSUE TITLE
How to automatically close Preview window

### ISSUE THREAD

**Issue by marxin** [prabirshrestha/vim-lsp#650]
![Screenshot from 2020-01-02 21-28-55](https://user-images.githubusercontent.com/2658545/71691210-07b03c00-2da7-11ea-93a0-01e73dd2b7fb.png)

Is it possible either not to display a Preview window in omni completion. Or can `vim-lsp` close it immediately after one selects a completion option?

```
nvim --version
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.1.2
Compilation: /usr/bin/cc  -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/abuild/rpmbuild/BUILD/neovim-0.4.3/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.4.3/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.4.3/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by prabirshrestha** [comment]
This is all based of your `.vimrc`.

To auto close preview window:

```
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
```

To never use preview

```
set completeopt-=preview
```

Refer to `:h completopt` for more details.

Feel free to send PR to imrpove docs.

**Comment by marxin** [comment]
Thank you very much for the nice explanation.
That's what I would like to see in the documentation. I'm going to add that.

**Comment by dezza** [comment]
Maybe it would make more sense if [g:lsp_preview_autoclose](https://github.com/prabirshrestha/vim-lsp/blob/master/doc/vim-lsp.txt#L359) not only worked for float/popup windows but also preview.

It seems like this is how it used to be, because if we follow the call-stack of [s:add_float_closing_hooks()](https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/autoload/lsp/ui/vim/output.vim#L197) into [lsp#ui#vim#output#closepreview()](https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/autoload/lsp/ui/vim/output.vim#L38) it actually calls `pclose` but that is never reached when `g:lsp_hover_ui = preview`, because [s:use_vim_popup or s:nvim_float is never true of course](https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/autoload/lsp/ui/vim/output.vim#L1-L2)

So to me it seems like the original idea was to close all 3 popup, preview, float, yet that code is never reached.

**Comment by dezza** [comment]
@prabirshrestha is this intentional?
