### ISSUE TITLE
Split LSP actions to separate files and provide common interface for them

### ISSUE THREAD

**Issue by hauleth** [prabirshrestha/vim-lsp#77]
This will allow to seamlessly provide commands in separation of others.

**Comment by prabirshrestha** [comment]
Yes. We should do this. The primary reason it isn't done yet is because I was in the process of discovering the apis and gathering requirements. I was creating functions as I needed them. Now that the most of the LSP features have been implemented and I'm familiar with it it makes sense to take a stab at this.

**Comment by prabirshrestha** [comment]
Closing the issue to cleanup the issues. Tracking it via https://github.com/prabirshrestha/vim-lsp/issues/624 instead.
