### ISSUE TITLE
add diagnostics signs.

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#87]
Although vim-lsp already supports `:LspDiagnostics` it would be good to have diagnostics signs working.

Seems like @tsufeki already got it running. https://github.com/tsufeki/vim-lsp/tree/diagnostic-signs. Any plans to send PR soon for this?

![image](https://user-images.githubusercontent.com/287744/34600232-483a5ace-f1ab-11e7-8392-9384072ffc5f.png)

Ideally I would like to have another vim plugin that manages these signs and vim-lsp uses it. This ways other plugins besides vim-lsp can also work on it. Had posted my initial thoughts to ale but got rejected. https://github.com/w0rp/ale/issues/517#issuecomment-320489193

Would love to have the api look somewhat like VsCodes' DiagnosticsCollection simple and clear. https://code.visualstudio.com/docs/extensionAPI/vscode-api#DiagnosticCollection

**Comment by prabirshrestha** [comment]
This is now supported by https://github.com/prabirshrestha/vim-lsp/pull/89 and https://github.com/prabirshrestha/vim-lsp/pull/90.

**Comment by nickspoons** [comment]
@prabirshrestha I realise this is already implemented but have you seen that ALE now does, in fact, support allowing external plugins to send diagnostics? ALE provides an `ALEWantResults` User autocmd, see w0rp/ale/issues/2017.

This is now being used in OmniSharp-vim, see [here](https://github.com/OmniSharp/omnisharp-vim/blob/master/plugin/OmniSharp.vim#L73) and [here](https://github.com/OmniSharp/omnisharp-vim/blob/master/autoload/ale/sources/OmniSharp.vim)

It could be worth providing an option to use ALE signs rather than vim-lsp signs. This would allow users who already use ALE for other things to use their same ALE sign configuration for LSP diagnostics, and also use their same mappings for navigating between diagnostic results.

Would you be interested in this, if I put together a PR?
