### ISSUE TITLE
Should rust omnicompletion work out of the box for Rust?

### ISSUE THREAD

**Issue by vext01** [prabirshrestha/vim-lsp#874]
Hi,

I've just moved my vim config from ale to vim-lsp. It's great so far! Thank you!

In python projects, omni completion works out of the box: when in insert mode, type `<C-x><C-o>` and the completion menu appears.

The same isn't true of Rust though. For example typing `use std::co<C-x><C-o>` does not offer any completions (I'd expect `std::collections` to be offered).

I've tried this on both Linux and OpenBSD -- same behaviour on both.

Is this expected? If not, I can boil it down to a minimal config and post it.

A friend has got rust completion working using `ncm2`, but as I understand, that shouldn't be necessary?

EDIT: All other Rust integrations (e.g. diagnostics, jump to def) are working great via vim-lsp and rust-analyzer.

Thanks

**Comment by dyamon** [comment]
Can confirm this behaviour as well using `vim-lsp`, `rls`, and `omnicompletion`. A few more details:
- I have a project using `amethyst` and that gets completed correctly (e.g., `use ameth<C-x><C-o>` or `use amethyst::<C-x><C-o>`). This dependency is explicitly stated in the `Cargo.toml` file;
- `use std::co<C-x><C-o>` doesn't return anything (not even `use st<C-x><C-o>` or `pri<C-x><C-o>`;
- `let var = "value"; var.<C-x><C-o>` doesn't work either. This doesn't work even for amethyst related variables;
- I tried to look at the log file generated by `vim-lsp` but I can't see any problem with the requests and answers (empty `List` when no completions are shown);
- I also tested all the above examples in VSCodium using `rls` and they behave as expected;
- At first I thought it was a problem with `vim-lsp-refresh_pattern`. I tried to play with it but couldn't fix the above errors.

**Comment by dyamon** [comment]
@vext01 so, according to the `rls` documentation ([here](https://github.com/rust-lang/rls/blob/master/debugging.md#racer-vs-compiler-issues)) if there is a problem with Racer (completion engine) and the standard library, the problem is most likely related to the `rust-src` component.

You might have installed your Rust distribution in a non standard way or the maybe the `rust-src` component is missing completely.

In my case I wasn't using `rustup` to install `rls` and `rust-src`, but the binary distribution provided by Gentoo (which does not include sources by default). Switching from `rust-bin` to `rust` package fixed my problem (and installed the sources as well).

Also note that, according to this [related issue](https://github.com/ycm-core/YouCompleteMe/issues/3478#issuecomment-620877597), `rls` has a configuration option to set the `sysroot` for `rustc`. If this is not set manually, it defaults to whatever is returned by `rustc --print sysroot`. The `src` path is [derived](https://github.com/rust-lang/rls/blob/da014485dfad208be2b97fb920a49d568274f0d9/rls-analysis/src/loader.rs#L80) from it and is `<sysroot>/lib/rustlib/src/rust`.

In my case this directory didn't exist at all, so, to check if this is a `rust-src` related problem, it might be worth checking if `$(rustc --print sysroot)/lib/rustlib/src/rust` exists.
