### ISSUE TITLE
ALE compatibility

### ISSUE THREAD

**Issue by w0rp** [prabirshrestha/vim-lsp#882]
Hello! One of the useful things I did in [ALE](https://github.com/dense-analysis/ale) a while ago was add [an API](https://github.com/dense-analysis/ale/blob/34adb997c6d1f41ebc5baa85e58e865da2939791/doc/ale.txt#L192) which makes it easy for other plugins to work together with ALE by sending diagnostics to ALE, so ALE can render them alongside results from external tools like `flake8` or `msgfmt` (PO files), or any external tool you can think of. [coc.nvim](https://github.com/neoclide/coc.nvim) uses this API to implement its `displayByAle` setting. (Though it doesn't use `ALEWantResults` or `ale#other_source#StartChecking()`, so it's not using the API totally correctly.)

Is anyone interested in either adding the hooks for ALE into this project, or making changes to vim-lsp so it's possible to create a `vim-lsp-ale` plugin which bridges the two together? I can help with this. The advantage is that you can use `vim-lsp` for all of your LSP needs and display problems in files alongside results of linter programs, all displayed in the same way.

**Comment by prabirshrestha** [comment]
Would be interested but it should be generic so vim-lsp doesn't have any references to ale. One can have `vim-lsp-ale` plugin which hooks into it.

Something like this: https://github.com/prabirshrestha/vim-lsp/pull/211#pullrequestreview-187274120.

Who maintains the source of truth ale or vim-lsp? Should it be maintained by vim-lsp but have hooks so that others can subscribe too? 

Given that vim-lsp now ships with [callbag.vim](https://github.com/prabirshrestha/callbag.vim) it should make it very easy to subscribe. I still need to create this api but I have thought of adding `lsp#stream()` api where one can listen to lsp events either internal from vim-lsp or from lsp servers instead of using `lsp#register_notification()`. Then we can have a flag that says `let g:lsp_diagnostics=1` which controls diagnostics but `let g:lsp_diagnostics_external_ui = 1` to not use vim-lsp ui for diagnostics. Then other plugins 

```vim
call lsp#callbag#pipe(
    \ lsp#stream(),
    \ lsp#callbag#filter({x->x.response.name == "textDocument/diagnostics"}),
    \ lsp#callbag#subscribe({x->s:update_diagnostics(x)}),
    \ )
```

We would also send internal `textDocument/didOpen` sort of messages so you can subscribe to other internal such as language server getting started/stopped, buffer getting open/close and so on.

If we send internal messages such as `:LspDiagnostics` then you can also hook into that command so you can open ALE diagnostics. This will also solve the problem of allowing to use CtrlP/FZF and [quickpick.vim](https://github.com/prabirshrestha/quickpick.vim) for other commands.

**Comment by prabirshrestha** [comment]
@w0rp implement `lsp#stream()` api. https://github.com/prabirshrestha/vim-lsp/pull/884.

I added an example of diagnostics that you can intercept. Most likely need to add more flags so vim-lsp doesn't change the ui such as adding signs and let ale handle it.

**Comment by w0rp** [comment]
That sounds like a good idea to me, and the best solution. You can have ways to hook into vim-lsp on your end, ways to hook into ALE on my end, and then someone can create another plugin that bridges the two together. I may have a go at it myself, just for fun.

**Comment by w0rp** [comment]
I'll leave a comment to appease stalebot. I will eventually come back to this, when I have the time.

**Comment by reorx** [comment]
Really looking forward to this feature, currently I'm using deoplete + vim-lsp + ale, with `let g:lsp_diagnostics_enabled = 0` option, everything works well, but since ale has to call `flake8` by itself, I can feel the lag comparing to use vim-lsp diagnostics without ale. ale does a great job in UI rendering, so I think the integration between ale and lsp outputs should be the best solution :)

**Comment by ipkiss42** [comment]
Posting a comment to keep the stalebot happy.

@w0rp: did you have a chance to work on this?

**Comment by rhysd** [comment]
Hey, I'm working on this. I finished first small implementation, but still seeing some timing issues. So the repository is private yet.

![tmp](https://user-images.githubusercontent.com/823277/114037488-00d27c00-98bc-11eb-936e-152306c83500.gif)

**Comment by w0rp** [comment]
I've been very busy with my day job and other life things, but let me know how you get on.

**Comment by rhysd** [comment]
@w0rp I have one question. Is it ok to call `ale#other_source#StartChecking` and `ale#other_source#ShowResults` even when `ALEWantResults` is not triggered? Since LSP's diagnostics results are notification, we can't know when receiving the notification. I want to set results when receiving the notification even if `ALEWantResults` is not triggered.

**Comment by rhysd** [comment]
@w0rp I created one issue related to this. Would you take a look?: https://github.com/dense-analysis/ale/issues/3690

**Comment by w0rp** [comment]
I'll have a look at that issue. I _think_ it's okay to call those functions without `ALEWantResults`. I set up that `User` `autocmd` so people know to check for issues when ALE asks for them. ALE ought not to clear the results you give it.

**Comment by rhysd** [comment]
I have made [vim-lsp-ale](https://github.com/rhysd/vim-lsp-ale) public. Closing this ticket.
