### ISSUE TITLE
Any plan to support substring and fuzzy matching in code completion ?

### ISSUE THREAD

**Issue by 123subhadeep** [prabirshrestha/vim-lsp#907]
Seems like this plugin only supports case insensitive exact prefix match, for code completion.

As an example: let's say obj has a function SomeFunction().

If I type dot after obj, it'll show SomeFunction only if an exact case insensitive prefix is pressed. (eg: S, So, Some, some, etc.)

But that function wont' show up if a non-prefix substring is pressed (eg: function), it doesn't support fuzzy matching either (eg: SoFun).
One may not remember the prefix for all the functions when there are a ton of them (let's say over 50), in that case it's a hard to use code completion.

It'll be great if we can to have code completion support for the above. 

Btw, is there a way to get the list of completion options ? that way I can just feed them to FZF and have fuzzy matching completion.
Thanks in advance.

**Comment by prabirshrestha** [comment]
You can use [asyncomplete-lsp](https://github.com/prabirshrestha/asyncomplete-lsp.vim) with custom pre-processors such as
* https://github.com/machakann/asyncomplete-ezfilter.vim
* https://github.com/tsufeki/asyncomplete-fuzzy-match

Latest vim now has `matchfuzzy` function built into vim so it is lot easier to now right fuzzy search. Since it is in `C` it should be very fast. Primary reason why I don't support it yet is that it is impossible to have fast fuzzy search in vimscript.

**Comment by 123subhadeep** [comment]
Thanks for getting back so quickly.

I use neovim btw, I will look at the links you posted when I get a chance. Thanks for your support again !

**Comment by prabirshrestha** [comment]
No plans to support it in vim-lsp. I do want it to natively support it in asyncomplete instead. For omnicomplete I want `set completeopt+=matchfuzzy` so it is most likely and ask in vim/neovim
