### ISSUE TITLE
Vim-lsp fails to complete without working in the root directory.

### ISSUE THREAD

**Issue by hhaoao** [prabirshrestha/vim-lsp#941]
What key steps did I miss? How can I set it to work properly in multi-level nested directories?

Directory Structure:
```
root
    --directory1
        --directory2
            --temp.cc
```

temp.cc
```cpp
#include <s>  //An error occurred while typing in the standard library, such as: <string>
```
#### vim plugin
```vim
Plug 'prabirshrestha/vim-lsp'
  Plug 'prabirshrestha/async.vim'
  Plug 'mattn/vim-lsp-settings'

" 代码完成
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

```

#### vim seting
```viml
" local clangd 
let g:lsp_settings = {
\  'clangd': {'cmd': ['clangd']},
\  'efm-langserver': {'disabled': v:false}
\}
```

#### vim messages
```log

简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
"F:\project\cpp\rein\src\coroutine\coroutine.cc" 13L, 246C
处理 function <SNR>18_recompute_pum[42]..<SNR>18_default_preprocessor 时发生错误:
第    6 行:
E716: Dictionary 中不存在键: asyncomplete_lsp_clangd
处理 function <SNR>18_recompute_pum[42]..<SNR>18_default_preprocessor 时发生错误:
第    6 行:
E116: Invalid arguments for function has_key(s:sources[l:source_name], 'filter')
处理 function <SNR>18_recompute_pum[42]..<SNR>18_default_preprocessor 时发生错误:
第    6 行:
E716: Dictionary 中不存在键: asyncomplete_lsp_clangd
处理 function <SNR>18_recompute_pum[42]..<SNR>18_default_preprocessor 时发生错误:
第    6 行:
E116: Invalid arguments for function has_key(s:sources[l:source_name], 'filter')
```

#### log files:
[1lsp_log.txt](https://github.com/prabirshrestha/vim-lsp/files/5602883/1lsp_log.txt)
[2asyncomplete_log.txt](https://github.com/prabirshrestha/vim-lsp/files/5602884/2asyncomplete_log.txt)

**Comment by prabirshrestha** [comment]
I had seen something similar with latest rust-analyzer. When debugged it further it seemed it was due to a bug in rust analyzer which caused it to panic. Your logs seems to be showing the same.

```
2020/11/26 20:02:21:["s:on_exit",1,"clangd","exited",-1073741819]
```

It is crashing in asyncomplete here https://github.com/prabirshrestha/asyncomplete.vim/blob/ed75b1c92fb144bbe236bfb4d60a98dccf637c58/autoload/asyncomplete.vim#L450. 

```vim
 if has_key(s:sources[l:source_name], 'filter')
```

When the server exits, it automatically unregisters itself as an asyncomplete source hence `s:source[l:source_name]` becomes undefined and due to async nature and debounce sometime in the future it asks to recompute the autocomplete items causing it to throw error.

I decided not to fix this since it was a bug in rust analyzer but now that I think of it more, it can happen anytime the server exits due to other crashes. Seems like it is better to improve this experience.

In `s:recompute_pum` around here can you make the following changes: 
https://github.com/prabirshrestha/asyncomplete.vim/blob/ed75b1c92fb144bbe236bfb4d60a98dccf637c58/autoload/asyncomplete.vim#L412

```vim
for [l:source_name, l:match] in items(s:matches)
        if !has_key(s:sources, l:source_name) | continue | endif " ignore sources that have been unregistered
        let l:startcol = l:match['startcol']
```

As for the actual why clangd is panicking I have no idea since the error doesn't seem useful. Might be try disabling `textDocument/documentHighlight`? The reason it is most likely occuring when you type is because once it hits the trigger character it will cause the didChange notification to be sent and ask for complete items at that point. Something could also be wrong with didChange on clangd.

```
2020/11/26 20:02:21:["<---(stderr)",1,"clangd",[" #0 0x00007ff6a4fc742e (D:\\msys64\\mingw64\\bin\\clangd.exe+0x4b742e)\r"," #1 0x00007ff6a4f83521 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x473521)\r"," #2 0x00007ff6a4f87c0c (D:\\msys64\\mingw64\\bin\\clangd.exe+0x477c0c)\r"," #3 0x00007ff6a4f89da3 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x479da3)\r"," #4 0x00007ff6a4f8e1a6 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x47e1a6)\r"," #5 0x00007ff6a4f90e7a (D:\\msys64\\mingw64\\bin\\clangd.exe+0x480e7a)\r"," #6 0x00007ff6a4f75a0b (D:\\msys64\\mingw64\\bin\\clangd.exe+0x465a0b)\r"," #7 0x00007ff6a4fba8a7 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x4aa8a7)\r"," #8 0x00007ff6a59fe3c3 (D:\\msys64\\mingw64\\bin\\clangd.exe+0xeee3c3)\r"," #9 0x00007ff6a59f8dc9 (D:\\msys64\\mingw64\\bin\\clangd.exe+0xee8dc9)\r","#10 0x00007ff6a50fac6b (D:\\msys64\\mingw64\\bin\\clangd.exe+0x5eac6b)\r","#11 0x00007ff6a50ff296 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x5ef296)\r","#12 0x00007ff6a50f4be0 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x5e4be0)\r","#13 0x00007ff6a513e1a5 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x62e1a5)\r","#14 0x00007ff6a513ceb1 (D:\\msys64\\mingw64\\bin\\clangd.exe+0x62ceb1)\r","#15 0x00007ff6a51ce"]]
2020/11/26 20:02:21:["s:on_exit",1,"clangd","exited",-1073741819]
```

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/asyncomplete.vim/pull/241
