### ISSUE TITLE
vim9 or lua

### ISSUE THREAD

**Issue by timsofteng** [prabirshrestha/vim-lsp#944]
Hello. I read in md some essential parts of code has been written in lua. Will you rewrite it into vim9 when it will release or not? Looks like soon vim and neovim will be to different to support plugins for both. I suppose devs who working on plugins should choose. So will you focus on new vim9 or stay with lua?

**Comment by prabirshrestha** [comment]
vim-lsp will be written in vimscript <= 8 with lua for code that needs perf. no plans to rewrite in vim9 as it doesn't work in neovim. 

@timsofteng not sure what you mean by different support for plugins. https://github.com/neovim/neovim/issues/12537 is minimal required for lua compat in vim and neovim which I have been contributing too. Rest are fancy apis and haven't ported it since I don't know if Bram will accept some of the patches.

**Comment by amadeus** [comment]
I see you were working on this vim9 version of lsp, although it hasn't been updated in a couple months:

https://github.com/prabirshrestha/vim-lsp/commits/native-lsp-client

What's the status on this branch?
